### ISSUE TITLE
Game crashing when picking Shrinking Draught at second boss

### ISSUE THREAD

**Issue by Luddeeeeeee** [The-Evil-Pickle/Replay-the-Spire#107]
The game instantly crashes when i pick up Shrinking Draught at the second boss.
Playing with the Construct so there might be an interaction issue there?

**Comment by Skrelpoid** [comment]
Probably related to jonasdasdefekte/The-Sage#21
It seems like Shrinking Draught is hardcoded for animations that use Spine, and will crash for Spriter animations
